export const CARDS_NAMES = [
    'cardBackRed.png', 
    'cardClubs_8.png', 
    'cardClubs_9.png', 
    'cardClubs_10.png', 
    'cardClubs_A.png', 
    'cardClubs_J.png', 
    'cardClubs_K.png', 
    'cardClubs_Q.png', 
    'cardDiamonds_8.png', 
    'cardDiamonds_9.png', 
    'cardDiamonds_10.png', 
    'cardDiamonds_A.png', 
    'cardDiamonds_J.png', 
    'cardDiamonds_K.png', 
    'cardDiamonds_Q.png', 
    'cardHearts_8.png', 
    'cardHearts_9.png', 
    'cardHearts_10.png', 
    'cardHearts_A.png', 
    'cardHearts_J.png', 
    'cardHearts_K.png', 
    'cardHearts_Q.png', 
    'cardSpades_8.png', 
    'cardSpades_9.png', 
    'cardSpades_10.png', 
    'cardSpades_A.png', 
    'cardSpades_J.png', 
    'cardSpades_K.png', 
    'cardSpades_Q.png'
] 

export const textStyle = {
    dropShadow: true,
    dropShadowAlpha: 0.2,
    fill: "white",
    fontFamily: "\"Lucida Sans Unicode\", \"Lucida Grande\", sans-serif",
    fontSize: 102,
    strokeThickness: 1
}